### ISSUE TITLE
Platba objednávky - chyba

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#1]
Po uhrazení objednávky platební bránou GoPay - platba převodem Fio, je označena jako že se spracovává a není vedena, jako zaplacená. Je to např. objednávka 9337. Občas se to stane, nepravidelně.

![Snímek obrazovky 2024-10-22 v 0 24 03](https://github.com/user-attachments/assets/3def47f2-c6c9-41f1-ae3c-f0c0a0f0e52a)

**Comment by Kosty-art** [comment]
Dobrý den,

objednávky fyzických produktů jsou i po zaplacení automaticky nastaveny jako Zpracovává se. Tento stav znamená, že objednávka je zaplacena, ale produkty ještě nejsou odeslány zákazníkovi a vyžadují akci ze strany obchodníka – přichystání, zabalení a odeslání zboží. Po platbě kartou jsou tyto objednávky ve stavu Zpracovává se také.
