### ISSUE TITLE
Sběr emailů

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#10]
- [ ] Texty nápovědy ve formulářích v banneru sběru emailu nejsou čitelné.
- [ ] V tlačítku chybí slovo novinky, je tam pouze Odebírat.
- [ ] Vrchní text může být klidně stejným písmem jako na referenčních stránkách.

![Image](https://github.com/user-attachments/assets/2f6657d9-4a35-4140-b549-293ee08c0e7f)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
