### ISSUE TITLE
Nastavení události

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#13]
Při změně nastavení události (např. datum, místo, ...) se změny neprojeví na výpisu události. Datum bude stačit, když se bude vypisovat ve formátu 24. 1. 2024.
![Image](https://github.com/user-attachments/assets/833fb405-9ec9-40df-aed7-f14ea5cecff5)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
