### ISSUE TITLE
Nezobrazovat karty u detailu živé akce

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#14]
Nezobrazovat karty u produktů (knihy a u živých akcí je čárka bez karet)
![Image](https://github.com/user-attachments/assets/01775955-9a41-46c1-b66a-745651e11145)

![Image](https://github.com/user-attachments/assets/f39a7adf-0f17-4ba3-80f3-aeb94ae3746e)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
