### ISSUE TITLE
Písma a rozestupy

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#15]
Písmo nadpisu produktu a kategorie je jiné, než na referenční stánce. Rozestup videa od hlavní nabídky je jiný, než na ref. stránce. Menu písma v hlavní nabídce je jiné, než na ref. stránce.
![Image](https://github.com/user-attachments/assets/2553bcb8-c3a4-4bc6-9b9e-ae35b9c438c7)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
