### ISSUE TITLE
Objednávka

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#16]
Orámování inputů: 1px solid #debete
Minimální velikost písma v objednávce, včetně inputů by měla být 16px
Barva písma inputů: black
Dále můžete odstranit celkové orámování a udělat to stejně jako jsou 
box-shadow: 0px 5px 25px 0px #A9A9A9;
Také bude vhodné odstranit ikony u nadpisů.

Výsledek může vypadat zhruba takto:

![Image](https://github.com/user-attachments/assets/e94872e8-d086-43e9-8891-8514802d675c)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
