### ISSUE TITLE
Příliš velké rozestupy

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#18]
V detailu produktu Woo jsou příliš velké rozestupy. 

Co se týče odsazení textů od okrajů, tak Google standard je 16px. Nyní je to 28,5px. Video se od okrajů odsazovat nemusí. Pokud Vám to video nepůjde, tak to dělat nemusíte.

![Image](https://github.com/user-attachments/assets/0fd932f9-29d1-4ee6-a996-ec7b9d3df00f)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
