### ISSUE TITLE
OK - Vzhled a funkce online kurzu

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#20]
Při zobrazení na mobilním zařízení po kliknutí na lekci v menu v online kurzu menu nezmizí. To bohužel znemožní prohlížení online kurzu. Proto to bude lepší zrušit a nechat online kurz ve standardním provedení od MasterStudy. Není třeba ani měnit barvy a písma (velikost a barvy), to by vyžadovalo více času a práce. Tlačítka můžou být modrá, stejně jako v MS včetně podbarvení. Mají to velice pěkně udělané a člověka to kurzem dobře vede.

![Image](https://github.com/user-attachments/assets/f9910f91-ee37-42a6-99c7-fe0c0dba070f)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
