### ISSUE TITLE
Moje online kurzy

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#23]
Pokud kliknu na moje online kurzy zobrazí se menu (Přihlášené kurzy, zprávy, mé certifikáty). Pokud kliknu na Přihlášené kurzy, zprávy nebo mé certifikáty levé menu zmizí a také u zpráv je šedé podbarvení. Myslím, že toto menu včetně těch statistik je zbytečné a v ideálním případě by mohla stránka vypadat jako na obr. níže. Pokud to půjde můžete dát položku mé certifikáty do menu vlevo. Pokud to nepůjde, tak nic každý si může stáhnout certifikát v poslední lekci online kurzu.

![Image](https://github.com/user-attachments/assets/4b636f27-1bf2-49fc-a6d6-0436b0611d79)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
