### ISSUE TITLE
Přetékání textu v pokladně

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#28]
Při menším rozlišení přetéká text v pokladně. Logo ČP a Balíkovny může být klidně bez textu, jen ikonka. ![Image](https://github.com/user-attachments/assets/9c39be11-685d-4bec-97f0-b5df681791e4)

![Image](https://github.com/user-attachments/assets/3fd39b70-9777-4930-9525-8a5d9043308e)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
