### ISSUE TITLE
Online kurz - Stránka produktu

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#3]
**Šablona vzhledu online kurzu se nezobrazuje, jako na referenčí stránce:**
- [ ] Vzdálonost nadpisů je příliš veliká
- [ ] Vzdálenost videa od pravého přehledu je veliká
- [ ] Jsou použity jiné písma (fonty, velikosti, barvy)
- [ ] Video je orámováno černě, nemělo by být
- [ ] Na tlačítku by mělo být napsáno "Koupit online kurz", aby si to zákazník nespletl s živou akcí.
- [ ] Položka Online kurzy by v menu měla být podbarvená.
- [ ] Na stránce chybí tlačítko "Koupit online kurz" úplně dole. Viz ref. stránky.
- [ ] V kompaktním zobrazení jsou kolem videa i obsahu po stranách příliš velké okraje (viz obr. dole)

**Nová stránka:**
![Image](https://github.com/user-attachments/assets/f2f71f81-8840-4589-a49b-c61f7ceabd4d)
![Image](https://github.com/user-attachments/assets/56f683fe-5ebc-4557-9093-5c533aa5c145)

**Referenční strána:**
![Image](https://github.com/user-attachments/assets/03b3d0a6-d1f3-48ac-b380-9c4acf6d22d1)

**Tlačítko dole:**
![Image](https://github.com/user-attachments/assets/28cf36a5-b8d8-46be-999e-97ad97efe6c4)

**Kompaktní zobrazení**
Nové stránky:
![Image](https://github.com/user-attachments/assets/b401c1ce-5832-4ca8-86fd-f6e4dbc91eb2)

Ref. stránky:
![Image](https://github.com/user-attachments/assets/34a88344-8ea4-4e97-a74c-b74ce9ac60e2)

**Comment by Kosty-art** [comment]
připraveno ke kontrole.

Jen bod: V kompaktním zobrazení jsou kolem videa i obsahu po stranách příliš velké okraje (viz obr. dole) / Našel jsem na internetu: Google ve svých Mobile Usability Guidelines (směrnicích pro mobilní použitelnost) doporučuje dostatečné mezery a zajištění toho, aby text nebyl těsně u okrajů. To je zvláště důležité pro použitelnost a mobilní SEO, jelikož Google sleduje mobilní použitelnost jako faktor hodnocení.
