### ISSUE TITLE
Barvy konverzní cesty + nadpis Objednávka a doprava

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#30]
Tlačítko upravit objednávku by němělo být barvou konverzní cesty a pokud to je možné, změnit text "Vaše objednávka" na "Objednávka a doprava". Na obrázku jsou vidět i další změny, ty ale dělat nemusíte, zkoušel jsem, jak by to vypadalo s linkami. Stačí jen barva tlačítka a nadpis.

![Image](https://github.com/user-attachments/assets/51c0af35-63bb-4b39-8092-30d0a5580f01)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
