### ISSUE TITLE
Objednávka odeslána

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#31]
Po zaplacení objednávky se zobrazí její rekapitulace, která je nepřehledná. Pokud to půjde tak můžete dodat linky do tabulky, aby to zlepšilo čitelnost a také nastavit maximální šířku tabulky na 700px, aby ceny nebyly daleko od názvů položek. Ceny zarovnat doprava.
![Image](https://github.com/user-attachments/assets/36ee6176-5692-4bf6-8fe5-80b90443dab5)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
