### ISSUE TITLE
Odeslání objednávky - legislativa

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#32]
Na stránce pokladny by z hlediska právního by měl být umístěn checkbox před tlačítkem odeslat objednávku a také možnost zapsat se do odběru novinek. Tlačítko by mělo zavazovat zákazníka k platbě. Šlo by to tam takto dodělat?

[ ] Souhlasím s **obchodními podmínkami**
Dodržujeme **zásady ochrany osobních údajů**.
Tlačítko: Odeslat a zaplatit

**Comment by Kosty-art** [comment]
připraveno ke kontrole

**Comment by xljan** [comment]
Bohužel z právního hlediska musí být na stránkách skutečně checkbox. Toto nebylo definováno ve smlouvě, proto Vám za to určitě zaplatím, ale být to tam musí.
A celé to může být zarovnáno na střed. Na webu je logika vlevo zpět, vpravo vpřed.

**Comment by xljan** [comment]
Nechci Vám zasahovat do functions.php, ale mělo by to být něco takového:

```
add_action( 'woocommerce_review_order_before_submit', 'pridej_checkbox_op' );

function pridej_checkbox_op() {
?>
  <div class="woocommerce-terms-and-conditions-wrapper">
    <input type="checkbox" id="souhlas_op" name="souhlas_op" class="woocommerce-form__input woocommerce-form__input-checkbox input-checkbox" required>
    <label for="souhlas_op" class="woocommerce-form__label woocommerce-form__label-for-checkbox checkbox">
      <span><?php echo __( 'Souhlasím s <a href="/obchodni-podminky/">obchodními podmínkami</a>', 'kyselove' ); ?></span>
    </label>
  </div>
<?php
}

// Zobrazení chybové hlášky, pokud není checkbox zaškrtnutý
add_action( 'woocommerce_checkout_process', 'zkontroluj_checkbox_op' );

function zkontroluj_checkbox_op() {
  if ( ! isset( $_POST['souhlas_op'] ) ) {
    wc_add_notice( __( 'Pro odeslání objednávky musíte souhlasit s obchodními podmínkami.', 'kyselove' ), 'error' );
  }
}
```

**Comment by Kosty-art** [comment]
připraveno ke kontrole
