### ISSUE TITLE
Recepty ve WooCommerce

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#33]
Myslel jsem, že obsah receptů by neměl být veden jako obchodovatelné položky, ale jako příspěvky ve WordPressu. 

Dělá mi to problémy v externích aplikacích, např. na mobilu je možné si nainstalovat aplikaci WooCommerce a spravovat objednávky a produkty v mobilu, což je pro mě velmi důležité na cestách a nyní to mám pomíchané (viz obr.). Hodně lidí nemá hotovost a tak jim vystavuji objednávky emailem, aby zaplatili přes účet. Nyní jsou v aplikaci všechny recepty smíchané s produkty, takže nemůžu tak rychle něco vyhledat.

Dále používám externí nástroje na účetnictví, které si automaticky nahrají všechny produkty z obchodu a umí vytvářet faktury, atd. Můj účetní by se tam měl také připojovat skrze nějaké api a stahovat všechny objednávky i produkty, kvůli skladu.

Chápu, že to dalo opravdu hodně práce, ale do budoucna by to mohlo dělat problémy, takže se to bude muset předělat. Teď je otázkou kdy a jak. Navrhuji tedy, že to necháme jak to je, uzavřeme tuto zakázku s tím, že s tím **souhlasím, že recepty budou jako položky ve WooCommerce**. Do budoucna můžeme obnovit spolupráci a uděláme novou zakázku, kde se to předělá třeba na plug-in "wp recipe maker", nebo něco podobného a tu si znovu naceníte. Budu k tomu mít jen pár připomínek o vzhledu receptů. Napíšu je za chvilku.

![Image](https://github.com/user-attachments/assets/828209cf-6380-407a-9fa7-e1e1e24df20b)

**Comment by Kosty-art** [comment]
Dobře, souhlasím
