### ISSUE TITLE
Nelze měnit krátký popis produktu (knihy)

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#38]
Ve výpisu knih, by měly být zobrazeny jejich popisy, které se nastavují v administraci jako krátký popis produktu. Tam jsou ale uloženy proporce knihy. Do budoucna bychom chtěli obchodovat více položek, třeba desítky i stovky a bude to obsluhovat několik lidí, kteří jsou zvyklí z běžných e-shopů editovat krátký popis a popis a proto bych toto chtěl mít správně. 

Navrhuji tedy založit Uživatelské pole book_data, do kterého budeme dávat HTML popis knihy. V šabloně si ho poté vytáhnete a vypíšete jednoduše, tímto kódem:

`<?php 
$proporce = get_post_meta( get_the_ID(), 'book_data', true ); 
echo $proporce; 
?>`

Následně se ve výpisu produktů (knih) může zobrazovat krátký popis.

![Image](https://github.com/user-attachments/assets/cf3cb4cb-95a7-4551-9dad-d78d4e5b62c6)

**Comment by Kosty-art** [comment]
![Image](https://github.com/user-attachments/assets/7bb22024-01ea-4fbf-a68c-d01d1565a1e3)
Nově nastavené nové pole Krátký popis produktů, který se bude zobrazovat na archive pages a dole je umístěno pole Informace o produktu.

**Comment by xljan** [comment]
Takto to skutečně není možné. Toto řešení neodpovídá standardní funkčnosti a logice WooCommerce a budeme se do budoucna potýkat se zásadnímy problémy. Počínaje špatně uvedeným meta description, což si můžete sám ověřit pohledem do zdrojového kódu stránky, dále špatnou funkcí pluginů a externích aplikací, které předpokládají, že stručný popis produktu bude v položce krátký popis. Vlastnosti produktu, jako je velikost, šířka, počet stran, nakladatel atd patří do uživatelských polí. Abych mohl web převzít musí to být opravené.

**Comment by xljan** [comment]
Toto je i u knih, když se podíváte do zdrojového kódu, tak najdete <meta name="description" content="[fooevents_info]">. V každém případě bude systém napojen na el. tržiště, např. na heureku a tam se berou krátké popisky nako popis produktu. Pluginy, které budou obchod spojovat s dalšími tržišti častokrát berou data přímo z databáze, takže to prostě obejít nelze. V krátkém popisu musí být krátký popis, s tím nic udělat nelze. Stejné je to i u Online kurzů.

**Comment by Kosty-art** [comment]
![Image](https://github.com/user-attachments/assets/63a5d607-28e7-4e5b-af76-efd25883fca5)
nově krátký popis zůstává jako krátký popis, který se bude zobrazovat na archive pages a pro informace o produktu je nově vytvořeno Informace o produktu,
