### ISSUE TITLE
Responzivní vzhled nefunguje

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#39]
Pokud zmenšuji detail knihy (obecně je to na všech stránkách), tak by měl jít prohlížeč zmenšit blízko obsahu, který by se neměl měnit, tak jako na [ref. stránkách](https://www.kyselove.cz/knihy/kvasena-zelenina-na-1008-zpusobu):
![Image](https://github.com/user-attachments/assets/a648901e-9b9b-4073-a4ac-9331bfd5371c)

Bohužel na novém webu to funguje tak, že se obsah zmenšuje ještě když okraje prohlížeče jsou velmi vzdálené od obsahu a ten se nevhodně deformuje:
![Image](https://github.com/user-attachments/assets/8bd71c5f-b31b-4065-8352-11a53f00ea08)

V momentě, kdy se okno přihlíží téměř obsahu, což je asi 1170px, tak může levý panel se základními informacemi skočit pod video:
![Image](https://github.com/user-attachments/assets/8d66110c-8018-45e5-9d35-95ff62c9c662)

Video má na ref stránkách nastavenou maximální šíři 811px. Je to z důvodu, aby nebylo příliš veliké a neořezávalo se ve svislém směru a zachovala se maximální uživatelská přívětivost.

**Comment by Kosty-art** [comment]
připraveno ke kontrole
