### ISSUE TITLE
Navigace webu

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#4]
**Vrchní menu**
- [ ] V menu jsou použity jiné typy písma (font, styl)
- [ ] Pokud kliknu na detail online kurzu, nebo produktu v menu zmizí podbarvení a uživatel neví v jaké položce menu je (viz obrázek 1)
- [ ] Menu by mělo být maximálně dvou-úrovňové, tzn. jedna vyjížděcí úroveň (viz obr. 2)
- [ ] Jdou do menu "O nás" dodat ikony?
- [ ] Druhé menu s kategoriemi by mělo být menší, tak jako je na ref. stránkách. Klidně ještě o něco menší, aby nezabíralo tolik místa. (obr 4)
- [ ] Otázkou je, co s tímto "podmenu" s kategoriemi dělat při kompaktním zobrazení? Pokud tam bude více kategorií, tak se tam nevejdou. Nejlepší bude, když se toto menu nebue v kompaktním zobrazení ukazovat.
- [ ] Logo mění velikost při změně rozlišení. Mělo by být stále stejně veliké 164x84 px. (viz obr. 4)
- [ ] Menu se pozdě přepíná do kompaktní verze a položka zdravé recepty v menu přetéká na nový řádek (obr. 4).
- [ ] Po najetí myši na ikonku košíku sezbarví do modra a téměř zmizí. Bude lepší, když se zabarví do oranžova, jako odkazy v kompaktním menu, aby to bylo v jednotném stylu:
![Image](https://github.com/user-attachments/assets/10789ad8-fe1a-434f-a540-caa880575277)

- [ ] Levé kompaktní menu může být celkově menší, aby na mobilech nedocházelo ke scrollování.

**Spodní menu v patičce**
- [ ] V navigaci v patičce se zobrazují jiné loga platebních metod. Je to povinné pro GoPay. Správné jsou v příloze obr. 3.
- [ ] Písmo položek Obchodní podmínky, Zpracování oso.... atd dejte prosím tučně, aby to lidé hned uviděli.
- [ ] Do menu patičky je třeba doplnit také odkaz Kontakt

**Další navigace**
- [ ] Nad názvem online kurzu by mělo být napsáno online kurz a ne název kategorie (viz obr. 1)
- [ ] Název a popis kategorie menu, by se něměl zobrazovat, viz škrtlý text na obr. 4. Je to u On. kurzů, Živých akcí a Knih. První je banner na sběr emailů a poté produkty.
- [ ] Vzhled sběru emailů by měl být menší, jako na ref. stránkách, viz obr. 4.

Obr 1:
![Image](https://github.com/user-attachments/assets/2316a48d-f4ff-45d4-9dc9-5d82c314dbcb)

Obr 2:
![Image](https://github.com/user-attachments/assets/9c0d515e-3253-4c58-ab75-6dbe29ce5a8b)

Obr 3:
![](https://www.kyselove.cz/templates/jsn_pixel_pro/images/icons/payment/all-payment.png)
![](https://www.kyselove.cz/templates/jsn_pixel_pro/images/icons/payment/gopay.png)

Obr 4:
![Image](https://github.com/user-attachments/assets/04c6382e-8dad-4f66-b658-d493ef56f306)

**Comment by Kosty-art** [comment]
připraveno ke kontrole.
