### ISSUE TITLE
Skladová dostupnost produktů

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#40]
Knihy máme na skladě, který je třeba evidovat a také dávat vědět zákazníkovi, jestli je produkt skladem, či nikoliv. Nejspíš bude nejvhodnější, aby se sklad vypisoval jako poslední, např. jako je vidět na obrázku. Pokud produkt není skladem, neměl by jít koupit.

![Image](https://github.com/user-attachments/assets/d531752d-e6b3-422a-bd13-13a4a8e9bfcd)

**Comment by Kosty-art** [comment]
zobrazení skladem se již objevuje nad tlačítkem přidat do košíku. V případě, že není skladem ji zakoupit nelze.
