### ISSUE TITLE
Tlačítko počet Ks

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#41]
Vaše řešení nastavení počtu kusů produktů s plus a mínus bohužel není dostatečně přívětivé pro lidi na mobilu. Lze se ukliknout doprostřed, nebo na tlačítko "Přidat do košíku". Navrhuji tedy udělat to selectem. No vlastně jsem to už udělal. Řešení je v souboru global/qantiti-input.php. Takže stačí odstranit tlačítka + - a zvětšit select na width: 70px; height: 45px; Výsledek, by měl vypadat následovně:

![Image](https://github.com/user-attachments/assets/6d23629d-20aa-4c38-a4bf-adb8b96a47e5)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
