### ISSUE TITLE
Výpis živé akce

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#45]
Na stránce podrobností s živou událostí se místo podrobností vpravo vedle videa zobrazuje krátký popis. Měl by se tam zobrazit termín akce, místo konnání, atd. Krátký popis události by se měl zobrazovat ve výpisu událostí.
![Image](https://github.com/user-attachments/assets/1ed70fa8-05b3-439d-aaa3-25b77906df9b)

**Comment by Kosty-art** [comment]
připraveno ke kontrole, stejné řešení jako u knih
