### ISSUE TITLE
Vážná chyba

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#46]
Po přihlášení k účtu s emailem testreg@kyselove.cz nastala na webu vážná chyba a od té doby nic nejde ani v novém anonymním okně prohlížeče. Asi po 2 minutách web začal fungovat.

![Image](https://github.com/user-attachments/assets/45da0e51-a803-4905-a072-cafaeb3c8d57)

**Comment by Kosty-art** [comment]
Dobrý večer, vkládal jsem Váš kód pro pokladnu do PHP a omylem jsem smazal při vkládání závorku, nyní by již mělo být vše v pořádku.
