### ISSUE TITLE
Stahování

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#47]
Pokud zvolím Můj účet -> Moje online kurzy, tak se v menu objeví položka Stahování. Když kliknu na objednávky, tak zmizí. Nic ke stažení nemáme, takže ji můžete odstranit.

![Image](https://github.com/user-attachments/assets/2bb46376-97ee-4d62-b9e4-00c7bc33a58d)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
