### ISSUE TITLE
Menu ujíždí s objednávkami

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#48]
Při posunu výpisu objednávek v administraci woocommerce ujíždí i meneu. Stačí popojet kouset dolu a potom vlevo. Není to nic zásadního
 Viz video.
![Image](https://github.com/user-attachments/assets/4482a7d4-d6eb-4b45-9977-8552a225e4d7)

**Comment by Kosty-art** [comment]
Chyba woocommerce, dělá to na všech e-shopech.

**Comment by xljan** [comment]
OK
