### ISSUE TITLE
Výpis živých akcí

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#49]
Kurz kvašené zeleniny v Praze bude uskutečněn 10.1.2025, ale vypisuje se v měsíci listopad 2024 a události jsou nad sebou a ne vedle sebe.

![Image](https://github.com/user-attachments/assets/b0e89bd4-d89a-4d80-8732-3b9f465a56ad)

**Comment by Kosty-art** [comment]
v PHP vytvořen kód, který podle data z FooEvents rozpozná měsíc a automaticky vytvoří nadpis a zařadí všechny kurzy z daného měsíce do společné sekce pod nadpis měsíce.
