### ISSUE TITLE
Online kurzy - Výpis produktů

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#5]
- [ ] Ve výpis online kurzů je příliš malé písmo u popisku kurzu. Je to 11.2 px, za což již google penalizuje stránky. Minimální písmo na webu by nemělo být menší než 13 px. U formulářů minimálně 16px. 
- [ ] Responzivní zobrazení panelu na sběr emailů se nezobrazuje správně:
Nový web: ![Image](https://github.com/user-attachments/assets/e4a31228-7b5a-4947-89b7-10c9e30af983)
Referenční web: ![Image](https://github.com/user-attachments/assets/07646865-6fbb-4ee9-ad9e-cc9ad711f8c2)
- [ ] Síla stínu položek může být více vidět .box-shadow: 0px 5px 25px 0px #A9A9A9;
- [ ] V kompaktním zobrazení se produkty zobrazují příliš úzké. Viz obr. 2. V ideálním případě se zobrazení přepne do menšího počtu sloupců dříve, než se začnou položky zužovat.

Obr. 1:
![Image](https://github.com/user-attachments/assets/63c23b2f-7d4e-40f0-8c7a-41d2b2cb756a)

Obr. 2:
![Image](https://github.com/user-attachments/assets/99a2c5b7-226e-4112-871d-f0a9173f436b)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
