### ISSUE TITLE
Dostupnost je nečitelná

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#51]
Dostupnost je nečitelná:
![Image](https://github.com/user-attachments/assets/e18af93a-bd8f-4748-90a0-dcd55ca68356)

Na ref. stránkách je pěkně vidět, že jsou produkty skladem. Je u toho uvedeno slovo Dostupnost. Budu rád, když to takto bude i na novém webu. Může to být i takto:

![Image](https://github.com/user-attachments/assets/907b76e5-f9c6-4a51-acae-c8e0664c8ef2)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
