### ISSUE TITLE
Počet Ks je blízko tlačítka přidat do košíku

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#52]
Na ref. stránkách je tlačítko počet Ks dostatečně vzdáleno od tlačítka přidat do košíku, aby nedošlo k omylu. Bude dobré, když to takto bude i na novém webu Šířka selectu 70px, margin-right: 20px:

![Image](https://github.com/user-attachments/assets/881158af-eedc-4f9e-b701-10140a904ebc)

**Comment by Kosty-art** [comment]
upraveno na width: 75 - aby se vešlo i dvojciferné číslo a margin na 25px. (20px bylo pořád blízko)
