### ISSUE TITLE
Tlačítko koupit uteklo dolu

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#53]
Na prodejní stránce online kurzu je tlačítko koupit příliš dole a také je jiná barva a velikost písma u Obsah kurzu / získáte:
![Image](https://github.com/user-attachments/assets/2c68822e-88f4-4979-b507-5950a3de219b)

Referenční stránka:
![Image](https://github.com/user-attachments/assets/89ac9166-0b94-41ed-ba82-856cf95ce915)

**Comment by Kosty-art** [comment]
toto je defaultně nastaveno MS LMS, nevím co s tím.

**Comment by xljan** [comment]
V pohodě, budeme víc psát do toho boxu vpravo, pak to bude vypadat dobře. Není to nic důležitého.
