### ISSUE TITLE
Online kurz - Nákup produktu

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#6]
Při nákupu online kurzu jste zvolil, že před nákupem se bude muset uživatel přihlásit, nebo vytvořit účet. Já s tím souhlasím, ale byl bych rád, kdyby byl průchod košíkem upřednostněn pro nové uživatele. V současné době se objeví po kliknutí na tl. Koupit kurz toto okno:
![Image](https://github.com/user-attachments/assets/4e239e27-94a4-46d6-9845-e5729dc65f8b)

Což je okno s přihlášením, již registrovaných uživatelů. Bylo by však vhodnější zobrazit toto okno:
![Image](https://github.com/user-attachments/assets/3caba1de-c1ae-485b-9419-32f4ba522bdb)

Aby uživatel nebyl zmaten a věděl co se děje, navrhuji změnit toto okno následovně:
![Image](https://github.com/user-attachments/assets/7203e021-9004-48cf-b8d6-9d0bc39eb6bd)

Po kliknutí na tlačítko další by se měl uživatel přesměrovat do objednávky, kde doplní zbývající údaje.

**Neplatná data**:
Pokud někdo vloží do formuláře email, který je již registrován systém vypíše následující:
![Image](https://github.com/user-attachments/assets/001a27f6-ecc3-483d-8254-47c525b58b8e)
Písmo je 12px, což je málo, google už by to penalizoval, proto je vhodné ho zvětšit na 13px a v nejlepším případě doplnit ještě textem. Přihlásit se **můžete zde**. A pokud by někdo klikl na můžete zde, dostal by se na ten samý sormulář, ale s přihalšovacími údaji, sem:
![Image](https://github.com/user-attachments/assets/4e239e27-94a4-46d6-9845-e5729dc65f8b)

**Comment by Kosty-art** [comment]
nevím jak docílit - MS LMS si sám generuje tyto přihlašovací a registrační formuláře i jejich pořadí (zde mi JS ani PHP nefunguje)
změnil jsem field error zprávy na 13px
