### ISSUE TITLE
Tlačítko počet osob

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#61]
U detailu živé akce se nezobrazuje tlačítko Počet osob, jako na ref. stránkách. Na stránce s knihami mi stačí počet kusů vedle tlačítka koupit, to je intuitivní a jasné, že je míněno Ks = počet knih, ale u živích akcí je třeba, aby funkce byla stejná, jako na ref. stránkách, protož "Ks" je pro zákazníky nepochopitelné.
![Image](https://github.com/user-attachments/assets/5df2ce80-3d54-4d18-8a2b-fa1578be6d1f)

**Comment by Kosty-art** [comment]
Dobrý den, zasílal jsem požadavek několika lidem a všichni se shodli, že v případě popisu tlačítka "Koupit vstupenku" počet kusů logiku dává. Když budu chtít jít na akci s několika lidmi a budu mít na tlačítku Koupit vstupenku, přece musí být jasné, že vyberu počet kusů vstupenek podle počtu lidí.

**Comment by xljan** [comment]
Pokud se jedná o vstupenky, tak máte pravdu, že Ks dává smysl. Když jsem o tom přemýšlel, tak jsem si představoval naše tlačítko Přihlásit se s počtem Ks, což by v zákazníkovy evokovalo, že je nějaký kus, což jsem nechtěl. Teď vidím, že je to Koupit vstupenku, to je dobrý nápad to přejmenovat na vstupenky a je to vyřešeno.

**Comment by xljan** [comment]
Pane Kosturo, chápu, že Ks je logické a lidé pochopí, že se jedná o počet vstupenek, ale zde je ještě jeden problém. Když si zákazník prohlíží obsah kurzu, oko jede z vrchu dolu. Přečte si termín kurzu, kde to bude, kdo to učí a poté narazí na položku počet osob, kde je i obrázek rodiny a v tomto okamžiku začne přemýšlet **koho může na událost pozvat, nebo doporučit. Kolik nás bude?**. V tomto bodě se Váš návrh významně liší od referenčních stránek. Jsem si jist, že na každém kurzu řešení s tlačítkem Ks může snížit počet přihlášených. Proto budu velmi rád, když se i v tomto bodě budou výsledné stránky podobat referenčním.

**Comment by Kosty-art** [comment]
Všiml jsem si, že na ref. stránkách nemáte umístěné tlačítko koupit i dole na stránce. V tomto případě nevím, jak tlačítko dole vymyslet tak, aby dávalo smysl. V tomto případě nelze moc přihlížet k nalezení položky počty osob při pohledu z vrchu dolu, kde je termín kurzu, kde to bude, kdo to učí a poté i obrázek rodiny, proto mě napadl kompromis - Udělat nahoře v sekci položku počet osob i s obrázkem, ve kterém bude uvedena informace: Podle počtu osob vyberte, kolik kusů vstupenek chcete zakoupit. Takto si zákazník uvědomí, kolik vstupenek potřebuje zakoupit i v případě, že se k tlačítku dostane i na konci stránky.
![Image](https://github.com/user-attachments/assets/307fd2f8-f939-4c82-8ba4-0538867d20f6)
