### ISSUE TITLE
Košík

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#7]
- [ ] Pro jednoduchost bude stačit, když se bude vypisovat pouze Mezisoučet, bez celkové ceny:
![Image](https://github.com/user-attachments/assets/97f3bf2b-5c0b-4f1c-be60-6559f82e39a9)

- [ ] Zarovnání cen, které se vypisují pod sebe by mělo být vždy vpravo:
![Image](https://github.com/user-attachments/assets/f729d578-25b6-48cd-ac2e-326428dc8f65)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
