### ISSUE TITLE
Odkaz produktu nefunguje všude

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#8]
Po kliknutí na spodní bílou část odkazu na produkt se nic neděje. Je třeba, aby byl celý prvek aktivní a zachytil kliknutí, nebo dotyk.
![Image](https://github.com/user-attachments/assets/05cb2230-1c01-4ff8-8c9c-f2092d34d7dc)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
