### ISSUE TITLE
Šířka výpisu živých akcí

### ISSUE THREAD

**Issue by xljan** [xljan/dev.kyselove.cz#9]
Ve výpisu živých akcí je velký rozestup sběru emailů a hlavní nabídky (což je i u dalších stránek s výpisy produktů) a také jsou příliš vysoké nadpisy měsíců.
![Image](https://github.com/user-attachments/assets/28b3fd91-7fbf-46b0-8846-3437eee0a0a6)

**Comment by Kosty-art** [comment]
připraveno ke kontrole
